### ISSUE TITLE
TODO list for Numo::Sparse::COO

### ISSUE THREAD

**Issue by mrkn** [mrkn/numo-sparse#4]
We want to make Numo::Sparse::COO a Ruby version of `scipy.sparse.coo_matrix` and `sparse.COO` in Python.

We have to cover all the features of `scipy.sparse.coo_matrix` and `sparse.COO` in Numo::Sparse::COO.

## TODOs:

- [x] Create COO tensor from Numo::NArray tensor.
- [ ] `arcsin`
- [ ] `arcsinh`
- [ ] `arctan`
- [ ] `arctanh`
- [ ] `argmax`
- [ ] `argmin`
- [ ] `asformat` (TODO: need to rename to more Ruby-ish name)
- [ ] `asfptype` (TODO: need red-float support)
- [ ] `astype` (TODO: need to rename to more Ruby-ish name)
- [ ] `ceil`
- [ ] `conjugate`
- [ ] `dup` (`copy` in SciPy)
- [ ] `count_nonzero`
- [ ] `deg2rad`
- [ ] `diagonal`
- [ ] `dot`
- [ ] `eliminate_zeros`
- [ ] `expm1`
- [ ] `floor`
- [ ] `getH` (TODO: more beter name)
- [ ] `shape`
- [ ] `getcol` (TODO: more better name)
- [ ] `getmaxprint` (TODO: maybe unnecessary)
- [ ] `getrow` (TODO: more better name)
- [ ] `log1p`
- [ ] `max`
- [ ] `maximum`
- [ ] `min`
- [ ] `minimum`
- [ ] `multiply`
- [ ] `nonzero`
- [ ] `power`
- [ ] `rad2deg`
- [ ] `reshape`
- [ ] `resize`
- [ ] `rint`
- [ ] `set_shape` (TODO: more better name)
- [ ] `setdiag` (TODO: more better name)
- [ ] `sign`
- [ ] `sin`
- [ ] `sinh`
- [ ] `sqrt`
- [ ] `sum`
- [ ] `sum_duplicates`
- [ ] `tan`
- [ ] `tanh`
- [ ] `to_narray` (`toarray` in SciPy)
- [ ] `to_bsr` (`tobsr` in SciPy; need to implement BSR format support)
- [ ] `to_csr` (`tocsr` in SciPy; need to implement CSR format support)
- [ ] `to_csc` (`tocsc` in SciPy; need to implement CSC format support)
- [ ] `to_dense` (alias to `to_narray`)
- [ ] `to_dia` (`todia` in SciPy; need to implement DIA format support)
- [ ] `to_dok` (`todok` in SciPy; need to implement DOK format support)
- [ ] `to_lil` (`tolil` in SciPy; need to implement LIL format support)
- [ ] `transpose`
- [ ] `T` (alias to `transpose`)
- [ ] `trunc`

## References:

- https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html
- https://sparse.pydata.org/en/latest/generated/sparse.COO.html
